printWidth: 80
tabWidth: 4
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
objectWrap: preserve
bracketSameLine: true
arrowParens: always
requirePragma: false
insertPragma: false
checkIgnorePragma: false
proseWrap: always
htmlWhitespaceSensitivity: ignore
vueIndentScriptAndStyle: false
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
